Adds documentation for the nodes in the data/dictionary namespace
Cranq-io/cranq-prototypes pull request #11
Opened 2021-12-02 08:25 UTC by amatiszcr

2021-12-02 09:05 UTC, danstocker approved these changes

2021-12-07 13:34 UTC, lvass74 commented on data/dictionary/item deleter (mutable)/85538251-c3cb-4dd8-abd5-920afaac7676.json
> +  "description": "Deletes an item from the dictionary by it's key.\nMutates input.\n\nIf the item is not found, the original dictionary is forwarded.\n\nExample A:\n1. { \"first\": 1, \"third\": 3, \
Typo: "it"s key" should be "its key"

2021-12-07 13:43 UTC, lvass74 commented on data/dictionary/item deleter/73a9fd6e-d594-4efc-a0ae-acf4ab89b577.json
> +  "description": "Deletes an item from a dictionary by it's key. \nIf the item is not found, the original dictionary is forwarded.\n\nExample A:\n1. { \"first\": 1, \"third\": 3, \"fifth\": 5 } @0 re
"it's key" should be "its key"

2021-12-07 13:44 UTC, lvass74 commented on data/dictionary/item getter/857aacdb-326e-4b2e-a261-5197b667e14f.json
> +  "description": "Retrieves an item's value by it's key from a dictionary.\nIf the item is not found, the inputs are sent via `not found`.\n\nExample A:\n1. { \"first\": 1, \"third\": 3, \"fifth\": 5
"its key"

2021-12-07 13:45 UTC, lvass74 commented on data/dictionary/item setter/3966e767-b7a7-4221-961d-338a13d18c57.json
> +  "description": "Sets an item's value by it's key in a dictionary.\nIf the item is not found, it will be created.\n\nExample A:\n1. { \"first\": 1, \"third\": 3, \"fifth\": 5 } @0 received via `dict
"its key"

2021-12-07 13:48 UTC, lvass74 commented on data/dictionary/items getter/83ac4d5d-9ac9-48d0-ae17-a5a77b18cfb6.json
> +        "type": "typeof`dict`[string][]",
As the dictionary"s values are of type any, I guess the `values` output port's type should be `any[]`. Not sure if this expression actually means the same.

2021-12-07 13:53 UTC, lvass74 commented on data/dictionary/json parser/6470bc83-fb15-4801-942a-6f6dbc46a908.json
>          "type": "string",
Tip: can be typeof `json`

2021-12-07 13:57 UTC, lvass74 commented on data/dictionary/left joiner/20ab24f4-9017-4cf1-9b44-45211ec3d074.json
> +        "description": "Receives the dictionary containing the keys to join to, and the values to join by.\n\nExample:\n{\"first\":\"first_id\", \"third\":\"third_id\", \"fifth\":\"fifth_id\"}"
I think "," is not necessary after "the keys to join to"

2021-12-07 14:01 UTC, lvass74 commented on data/dictionary/left joiner/20ab24f4-9017-4cf1-9b44-45211ec3d074.json
> +        "description": "Receives the dictionary containing the values to join to, and the keys to join by.\n\nExample:\n{\"first_id\":1, \"second_id\":2, \"third_id\":3}"
I think the correct description would be:
"Receives the dictionary containing the keys to join by and the values to join."
... unless I misunderstood :)

2021-12-07 14:03 UTC, lvass74 commented on data/dictionary/left joiner/20ab24f4-9017-4cf1-9b44-45211ec3d074.json
> +        "type": "{string:typeof`b`[string]}",
Does this means the same as {string:any} ?

2021-12-07 14:11 UTC, lvass74 commented on data/dictionary/values getter/3419d082-1bea-4e6b-8dfb-47eabfe792b0.json
> +        "description": "Receives to dictionary to extract the values from.\n\nExample:\n{ \"first\": 1, \"third\": 3, \"fifth\": 5 } "
Receives **the** dictionary

2021-12-07 14:12 UTC, lvass74 requested changes
Submitted a couple of comments regarding typos or text corrections.

2021-12-16 12:05 UTC, lvass74 commented on data/dictionary/items getter/83ac4d5d-9ac9-48d0-ae17-a5a77b18cfb6.json
> +        "type": "typeof`dict`[string][]",
That's fine, we agreed that output ports should refer to input port's type whenever possible to keep types statically analyzable.
So don't change this.

2021-12-16 12:06 UTC, lvass74 commented on data/dictionary/left joiner/20ab24f4-9017-4cf1-9b44-45211ec3d074.json
> +        "type": "{string:typeof`b`[string]}",
It's fine, don't change it.

2021-12-29 10:17 UTC, amatiszcr commented
> Submitted a couple of comments regarding typos or text corrections.

fixed

2021-12-29 10:24 UTC, merged