Crpl 2865 put endpoint lesson
Cranq-io/cranq-prototypes pull request #112
Opened 2022-11-02 10:28 UTC by danstocker

2022-11-02 14:33 UTC, csabee1979 commented on io/http/server/utils/json request body parser/d61c432a-5b9e-483c-a103-5bb0c8f69748.json
> +        "description": ""
Should has description.

2022-11-02 14:33 UTC, csabee1979 commented on io/http/server/utils/json request body parser/d61c432a-5b9e-483c-a103-5bb0c8f69748.json
> +        "type": "any",
Should has description.

2022-11-02 14:36 UTC, csabee1979 commented on tutorials/get request/get sum handler/45e20f72-9709-4b81-897f-c21ee6be09fa.json
> +    "internal": true
Should be locked.

2022-11-03 08:43 UTC, csabee1979 approved these changes

2022-11-03 09:00 UTC, lvass74 requested changes

2022-11-03 11:11 UTC, danstocker commented on data/shared store/98a9e940-ff79-4331-b30e-ce1970390ad0.json
> +        "type": "{\"storeId\": string, \"data\": any}",
fixed

2022-11-03 11:11 UTC, danstocker commented on data/shared store/98a9e940-ff79-4331-b30e-ce1970390ad0.json
> +        "df286b60-2beb-4138-a6b2-667612bccc17": "const {storeId, data: value} = data;\nif (value === undefined) {\n  // reading\n  const store = shared[storeId];\n  if (store === undefined) {\n    ou
fixed

2022-11-03 14:28 UTC, lvass74 approved these changes

2022-11-03 15:46 UTC, merged