CRPL-2930: Add documentation to Pancake nodes.
Cranq-io/cranq-prototypes pull request #115
Opened 2022-11-08 10:46 UTC by gyhevizi

2022-11-15 14:35 UTC, danstocker requested changes

2022-11-15 14:35 UTC, danstocker commented on blockchain/ethereum/pancakeswap/wbnb deployer/0953af1d-ae69-47fe-aa66-085699649f88.json
> +        "description": "ends out any error that happened during compilation or deployment."
"Sends out..."?

2022-11-16 18:43 UTC, gyhevizi commented on blockchain/ethereum/pancakeswap/wbnb deployer/0953af1d-ae69-47fe-aa66-085699649f88.json
> +        "description": "ends out any error that happened during compilation or deployment."
ugly typo :-(

2022-11-17 13:47 UTC, danstocker approved these changes

2022-11-17 16:03 UTC, csabee1979 approved these changes

2022-11-22 09:28 UTC, merged