CRPL-2981: Added erc1155presetminterpauser abi prototype
Cranq-io/cranq-prototypes pull request #121
Opened 2022-11-22 14:25 UTC by gyhevizi

2022-11-28 16:29 UTC, lvass74 requested changes

2022-11-28 16:29 UTC, lvass74 commented on blockchain/ethereum/contracts/erc1155/erc1155presetminterpauser abi/0b58f32d-0aac-454c-bf10-cbf22fabc5fa.json
> +  "description": "Holds the ABI of the ERC1155presetminterpauser abi contract.",
"Holds the ABI of the ERC1155PresetMinterPauser ~~abi~~ contract."

2022-11-28 16:29 UTC, lvass74 commented on blockchain/ethereum/contracts/erc1155/erc1155 abi/aa6191bb-c26c-49d0-a597-93bd97294506.json
> +  "description": "Holds the ABI of the ERC1155 contract interface.",
Is the "interface" term required? It seems like a duplicate to me as the term ABI already contains it.

2022-11-28 16:29 UTC, lvass74 commented on blockchain/ethereum/contracts/erc1155/erc1155presetminterpauser abi/0b58f32d-0aac-454c-bf10-cbf22fabc5fa.json
> +  "name": "blockchain/ethereum/contracts/erc1155/erc1155presetminterpauser abi",
Should the name be camelcased? like "blockchain/ethereum/contracts/erc1155/ERC1155PresetMinterPauser ABI"

2022-12-02 14:17 UTC, csabee1979 approved these changes

2022-12-02 16:23 UTC, csabee1979 approved these changes

2022-12-05 07:19 UTC, lvass74 approved these changes

2022-12-05 07:26 UTC, merged