Adds Waiting List API V2 tutorial with it's dependencies
Cranq-io/cranq-prototypes pull request #124
Opened 2022-11-25 09:51 UTC by amatiszcr

2022-11-29 08:10 UTC, lvass74 requested changes
Review still in progress...

2022-11-29 08:10 UTC, lvass74 commented on data/array/first item getter (with not found)/e408f545-5648-47e7-9392-6c39c0dd14d1.json
> +  "name": "data/array/First item getter (with not found)",
Better to extend the current "data/array/First item getter" with not found output port.

2022-11-29 08:10 UTC, lvass74 commented on data/array/type tester fork/19aa85fb-32fd-4877-a6c8-96aa1865e89e.json
> +        "name": "on array",
Other typed fork keep the output ports named as `on true` and `on false`. For consistency we could use this same naming scheme here too.

2022-11-29 08:10 UTC, lvass74 commented on tutorials/waiting list api v2/common/at records to subscription converter/ed3b57f7-f7db-418e-a564-ce43841d6146.json
> +          "name": "first item getter (with not found) B",
better node name?

2022-11-30 08:19 UTC, lvass74 requested changes

2022-11-30 08:19 UTC, lvass74 commented on tutorials/waiting list api v2/resource/subscribe/token setter/f0b00122-f92d-4d12-8453-e3d083fad9ba.json
> +  "name": "tutorials/Waiting list API V2/resource/subscribe/token setter",
From the namespace of this prototype I expected it to be internal but it is public (reusable). Is this intentional?

2022-11-30 08:19 UTC, lvass74 commented on tutorials/waiting list api v2/resource/validate/3af9300a-c73a-4c13-9683-4e6983bec65e.json
> +        "description": "[Inherited from port `params` of `save to AirTable`] \n[Inherited from port `params` of `record inserter`] \nReceives the authentication & table parameters required to constru
Review or clear

2022-11-30 08:19 UTC, lvass74 commented on tutorials/waiting list api v2/resource/validate/is validated fork/query airtable/filter builder/8433bdf5-e2b8-4aff-a9ae-6fab14e404ee.json
> +        "description": "[Inherited from port `value` of `builder (key & value)`] \nReceives the value to assign to all items.\n\nExample:\n1"
Review or clear

2022-11-30 08:19 UTC, lvass74 commented on tutorials/waiting list api v2/resource/validate/is validated fork/query airtable/filter builder/8433bdf5-e2b8-4aff-a9ae-6fab14e404ee.json
> +        "description": "[Inherited from port `filled` of `custom template filler`] \nSends the template string with replaced parameters.\n\nExample:\n\"Hello world!\""
Review or clear

2022-11-30 08:19 UTC, lvass74 commented on tutorials/waiting list api v2/resource/validate/response builder/6405424b-d890-47a2-a565-52554ab2cb7b.json
> +                "description": "undefined\nundefined"
Clear undefined values

2022-11-30 15:14 UTC, amatiszcr commented on tutorials/waiting list api v2/common/is validated fork/519c16b7-898b-49eb-bff4-87c52e1cc55b.json
> +        "name": "not validated",
As above, but will add "on"

2022-12-01 09:10 UTC, lvass74 approved these changes

2022-12-01 09:29 UTC, merged