Feature/crpl 2757 b token deployment
Cranq-io/cranq-prototypes pull request #94
Opened 2022-09-26 08:55 UTC by gyhevizi

2022-09-27 08:29 UTC, lvass74 requested changes

2022-09-27 08:29 UTC, lvass74 commented on blockchain/ethereum/contracts/erc721/presets/erc721presetminterpauserautoid deployer/contract preset/a146eef9-b442-42f6-b31c-c19bfc1ee593.json
> +        "5c2df9e2-9902-488b-9381-5474fb89b84b": "//  number-like keys are not allowed since they\n/// do not preserve the strict key order\nif (Object.keys(data).some((x)=>!isNaN(x))){\n  throw new E
Converting a dictionary to an array using Object.values does not guarantee the order of the elements in the output array. Values will get into the array by order of creation that is up to the user thus non deterministic.

```
["name", "symbol", "baseTokenURI"].map((key) => data[key].toString())
```

2022-09-29 13:47 UTC, csabee1979 commented on blockchain/ethereum/contracts/compile and deploy contract preset/f4f89c90-1285-4803-b3c8-530254056164.json
> +  "name": "blockchain/ethereum/contracts/compile and deploy contract preset",
Protoype name should be start uppercase: Compile and deploy contract preset

2022-09-29 13:49 UTC, csabee1979 commented on blockchain/ethereum/contracts/compile and deploy contract preset/f4f89c90-1285-4803-b3c8-530254056164.json
> +        "description": "[Inherited from port `events` of `contract deployer`] \nMultiplexed events. Useful for monitoring progress.\nUse Demultiplexer to separate them."
On resusable prototye I would avoid the automatically generated [Inherited ...] text.

2022-09-29 13:49 UTC, csabee1979 commented on blockchain/ethereum/contracts/compile and deploy contract preset/f4f89c90-1285-4803-b3c8-530254056164.json
> +        "description": "[Inherited from port `compile settings` of `splitter B`] \nSends input data split into individual fields."
On resusable prototye I would avoid the automatically generated [Inherited ...] text.

2022-09-29 13:50 UTC, csabee1979 commented on blockchain/ethereum/contracts/compile preset/bf676a5e-7de7-47bb-9a9e-d9b15bedebe3.json
> +  "name": "blockchain/ethereum/contracts/compile preset",
Name should start uppercase.

2022-09-29 13:51 UTC, csabee1979 commented on blockchain/ethereum/contracts/compile preset/bf676a5e-7de7-47bb-9a9e-d9b15bedebe3.json
> +        "description": "[Inherited from port `value` of `item getter`] \nIf found, sends the value corresponding to the specified key.\n\nExample:\n1"
I would remove the [Inherited...] part.

2022-09-29 13:55 UTC, csabee1979 commented on blockchain/ethereum/contracts/contract preset/c791825d-ced0-4354-b066-d8488511dd4b.json
> +  "name": "blockchain/ethereum/contracts/contract preset",
Name should start uppercase.

2022-09-29 13:55 UTC, csabee1979 commented on blockchain/ethereum/contracts/erc20/internal/convert supply to 18 digits/e9b1083e-70b6-420a-97a7-a693670a8f0e.json
> +  "name": "blockchain/ethereum/contracts/erc20/internal/convert supply to 18 digits",
Name should start uppercase.

2022-09-29 13:57 UTC, csabee1979 commented on blockchain/ethereum/contracts/flat compiler/0823d223-40ba-4e1a-b408-91f620a4b543.json
> +  "name": "blockchain/ethereum/contracts/flat compiler",
Name should start uppercase.

2022-09-30 14:10 UTC, csabee1979 approved these changes

2022-09-30 14:11 UTC, merged